elasticsearch:
  host: 127.0.0.1
  port: 9200
# datasource
spring:
  datasource:
    url: jdbc:mysql:///goods?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.atguigu.entity

